mysite/urls.py
from datetime import datetime
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
import django.contrib.auth.views
from app.views import TermekAutocomplete
from app.views import BeszallitoAutocomplete
import app.views
import debug_toolbar

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = [
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password/$', app.views.change_password, name='change_password'),

    # API URL
    # Termék értékesítés termék keresés
    url(r'^api/get_termek/$', app.views.get_termek, name='get_termek'),

    url(r'^termek-autocomplete/$', TermekAutocomplete.as_view(), name='termek-autocomplete', ),

    # Bevételezés beszállító keresés
    url(r'^beszallito-autocomplete/$', BeszallitoAutocomplete.as_view(), name='beszallito-autocomplete', ),

    # Termékek lista
    url(r'^api/get_termekapi/$', app.views.get_termek_api, name='get_termekapi'),

    # Termékkategórai lista
    url(r'^api/get_termekkategoria_api/$', app.views.get_termekkategoria_api, name='get_termekkategoria_api'),

    # Termék gyarto lista
    url(r'^api/get_termekgyarto_api/$', app.views.get_termekgyarto_api, name='get_termekgyarto_api'),


    # Alap URL
    url(r'^$', app.views.index, name='index'),
    url(r'^beszallito/$', app.views.beszallito_list, name='beszallito_list'),
    url(r'^beszallito/new$', app.views.beszallito_new, name='beszallito_new'),
    url(r'^beszallito/(?P<pk>[0-9]+)/edit$', app.views.beszallito_edit, name='beszallito_edit'),
    url(r'^bevetel/new$', app.views.bevetel_new, name='bevetel_new'),

    url(r'^termek/$', app.views.termek_list, name='termek_list'),
    url(r'^termek/new$', app.views.termek_new, name='termek_new'),
    url(r'^termek/(?P<pk>[0-9]+)/edit$', app.views.termek_edit, name='termk_edit'),

    url(r'^termek-ertekesites/(?P<pk>[0-9]+)/show/$', app.views.termek_ertekesites, name='termek_ertekesites'),
    url(r'^termekatvezetes$', app.views.termek_atvezetes, name='termek_atvezetes'),

    url(r'^termekkategoria/$', app.views.termekkategoria_list, name='termekkategoria_list'),
    url(r'^termekkategoria/new$', app.views.termekkategoria_new, name='termekkategoria_new'),
    url(r'^termekkategoria/(?P<pk>[0-9]+)/edit$', app.views.termekkategoria_edit, name='termekkategoria_edit'),

    url(r'^termekgyarto/$', app.views.termekgyarto_list, name='termekgyarto_list'),
    url(r'^termekgyarto/new$', app.views.termekgyarto_new, name='termekgyarto_new'),
    url(r'^termekgyarto/(?P<pk>[0-9]+)/edit$', app.views.termekgyarto_edit, name='termekgyarto_edit'),

    url(r'^dokumentum/(?P<pk>[0-9]+)/list$', app.views.dok_list, name='dok_list'),
    url(r'^dokumentum/(?P<pk>[0-9]+)/new$', app.views.dok_new, name='dok_new'),
    url(r'^dokumentum/(?P<pk>[0-9]+)/(?P<termek_id>[0-9]+)/del$', app.views.dok_del, name='dok_del'),

    url(r'^termekimportfel/$', app.views.termek_import_feltolt, name='termek_import_feltolt'),
    url(r'^termekimport/$', app.views.termek_import, name='termek_import'),

    url(r'^webarmod/$', app.views.web_ar_mod, name='web_ar_mod'),
    url(r'^email/$', app.views.email, name='email'),
    url(r'^termekosszdb/$', app.views.email_termek_osszdb, name='email_termek_osszdb'),

    # Export URL
    url(r'^export_termek/$', app.views.export_termek, name='export_termek'),
    url(r'^export_ertekesit/$', app.views.export_ertekesit, name='export_ertekesit'),
    url(r'^export_bevetel/$', app.views.export_bevetel, name='export_bevetel'),
    url(r'^export_raktarkeszlet/$', app.views.export_raktarkeszlet, name='export_raktarkeszlet'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),]

app/forms/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from app.models import Raktar
from app.models import Ertekesit
from app.models import Beszallito
from app.models import Dokumentum
from app.models import Termek
from app.models import TermekKategoria, TermekGyarto
from dal import autocomplete


class BootstrapAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Név'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': 'Jelszó'}))


class TermekSearchForm(forms.Form):
    autocomplete = forms.CharField(label='Keres: ', max_length=100)
    autocomplete_id = forms.IntegerField(required=False)


class DokForm(forms.ModelForm):
    dok_nev = forms.CharField(required=True, label="Dokumentum neve")
    dokfile = forms.FileField(label='Feltöltés')

    class Meta(forms.ModelForm):
        model = Dokumentum
        fields = ('dok_nev', 'dokfile')


class TermekForm(forms.ModelForm):
    termek_nev = forms.CharField(label='Termék neve: ', max_length=255, required=True)
    gyari_cikkszam = forms.CharField(label='Gyári cikkszám: ', max_length=255, required=True)
    sajat_cikkszam = forms.CharField(label='Saját cikkszám: ', max_length=255, required=False)
    ar_web_netto = forms.DecimalField(label='Webes bruttó ár: ', required=True)
    ar_bolt_brutto = forms.IntegerField(label='Bolti bruttó ár: ', required=True)
    elhelyezes = forms.CharField(label='Elhelyezés: ', max_length=255, required=False)
    min_keszlet = forms.DecimalField(label='Minimum készlet: ', required=True)
    mennyisegi_egyseg = forms.ChoiceField(
        required=True,
        label="Mennyiségi egység",
        widget=forms.Select,
        choices=Termek.MENNYISEGI_EGYSEG,
    )
    web_link = forms.URLField(label='Web link: ', max_length=255, required=False)
    termekkategoria = forms.ModelChoiceField(queryset=TermekKategoria.objects.all(), empty_label="Kérem válasszon", required=True, label="Termékkategória")
    termekgyarto = forms.ModelChoiceField(queryset=TermekGyarto.objects.all(), empty_label="Kérem válasszon", required=False, label="Termék gyártó")

    aktiv = forms.BooleanField(label='Aktív: ', initial=True, required=False)
    megjegyzes = forms.CharField(required=False, label="Megjegyzés", widget=forms.Textarea)

    class Meta(forms.ModelForm):
        model = Termek
        fields = ('__all__')


class TermekKategoriaForm(forms.ModelForm):
    termekkategoria = forms.CharField(label='Termékkategória neve: ', max_length=255, required=True)

    class Meta(forms.ModelForm):
        model = TermekKategoria
        fields = ('__all__')


class TermekGyartoForm(forms.ModelForm):
    termekgyarto = forms.CharField(label='Termék gyártó neve: ', max_length=255, required=False)

    class Meta(forms.ModelForm):
        model = TermekGyarto
        fields = ('__all__')


class ErtekesitForm(forms.ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(ErtekesitForm, self).__init__(*args, **kwargs)
        self.fields['raktar'].queryset = Raktar.objects.filter(user=current_user)
        self.fields['raktar'].empty_label = None
        self.fields['raktar'].required = True

    eladas_mennyiseg = forms.DecimalField(label='Mennyiség: ', required=True)
    ar_eladas_brutto = forms.IntegerField(label='Eladási ár: ', required=True)
    # raktar = forms.ModelChoiceField(queryset= Raktar.objects.filter(user=current_user), required=True, label='Raktárból: ', empty_label=None)
    megjegyzes = forms.CharField(required=False, label="Megjegyzés", widget=forms.Textarea)

    class Meta(forms.ModelForm):
        model = Ertekesit
        fields = ('raktar', 'eladas_mennyiseg', 'ar_eladas_brutto', 'megjegyzes')


class BeszallitoForm(forms.ModelForm):
    beszallito_nev = forms.CharField(label='Beszállító neve: ', max_length=255, required=True)
    beszallito_cim = forms.CharField(label='Beszállító címe: ', max_length=255, required=False)
    beszallito_ugyintezo = forms.CharField(label='Ügyintéző: ', max_length=255, required=False)
    beszallito_email = forms.EmailField(label='Email cím: ', max_length=255, required=False)
    beszallito_telefon = forms.CharField(label='Telefon: ', max_length=255, required=False)
    megjegyzes = forms.CharField(required=False, label="Megjegyzés", widget=forms.Textarea)

    class Meta(forms.ModelForm):
        model = Beszallito
        fields = ('beszallito_nev', 'beszallito_cim', 'beszallito_ugyintezo', 'beszallito_email', 'beszallito_telefon', 'megjegyzes')


class BeveteltermekForm(forms.Form):
    # termek = forms.ModelChoiceField(queryset=Termek.objects.all(), widget=autocomplete.ModelSelect2(url='termek-autocomplete'))
    # termek = forms.ModelChoiceField(queryset=Termek.objects.all(), empty_label="Kérem válasszon", required=True, label="Termék")
    termek = forms.CharField(required=True, label="Termék")
    termek_id = forms.CharField(required=True, label="Termék_id", widget=forms.HiddenInput())
    raktar = forms.ModelChoiceField(queryset=Raktar.objects.all(), empty_label="Kérem válasszon", required=True, label="Raktár")
    bevetel_mennyiseg = forms.DecimalField(label='Mennyiség: ', required=True)
    ar_bevetel_netto = forms.DecimalField(label='Nettó ár: ', required=False)


class BevetelalapForm(forms.Form):
    # beszallito = forms.CharField(required=True, label="Beszállító")
    # beszallito = forms.ModelChoiceField(queryset=Beszallito.objects.all(), required=True, label="Beszállító")
    beszallito = forms.ModelChoiceField(queryset=Beszallito.objects.all(), widget=autocomplete.ModelSelect2(url='beszallito-autocomplete'))
    bevetel_datum = forms.DateField(required=True, label="Bevételezés dátuma", widget=forms.TextInput(attrs={'class':'datum'}))
    szallitolevel_szam = forms.CharField(label='Szállítólevél száma: ', max_length=255, required=False)
    megjegyzes = forms.CharField(required=False, label="Megjegyzés", widget=forms.Textarea(attrs={'rows': 4}))
    # termekek = TermekFormset()


# Termék átvezetés Formok
class TermekAtvazetAlapForm(forms.Form):
    raktarbol = forms.ModelChoiceField(queryset=Raktar.objects.all(), empty_label="Kérem válasszon", required=True, label="Raktárból")
    raktarba = forms.ModelChoiceField(queryset=Raktar.objects.all(), empty_label="Kérem válasszon", required=True, label="Raktárba")


class TermekAtvezetTermekForm(forms.Form):
    termek = forms.CharField(required=True, label="Termék")
    termek_id = forms.CharField(required=True, label="Termék_id", widget=forms.HiddenInput())
    mennyiseg = forms.DecimalField(label='Mennyiség: ', required=True)


class TermekImport(forms.Form):
    termekek = forms.FileField(label='Feltöltés', help_text='csv fájl, utf-8 BOM nélkül, az első sort törölni kell a mintából, <a href="/media/export/termek_import_minta.csv">Minta fájl</a>')

app/templates/app/beszallito_new.html
{% extends "app/layout.html" %}

{% block content %}

<h3 style="margin-left:40px;">Új beszállító létrehozása</h3><br>

<div class="col-md-6">
    {% load bootstrap3 %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        <button type="submit" class="save btn btn-primary">Létrehoz</button>
    </form>
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading"><h5 class="panel-title">Termék értékesítés - Termék keresés</h5></div>
    <div class="panel-body">
        <br>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6">
                    <form id="termek_keres_form" action="/" method="post">
                        {% csrf_token %}
                        {% load widget_tweaks %}
                        {{ form.autocomplete|add_class:"form-control"|attr:"autofocus"|attr:"placeholder:Cikkszám, Termék neve"}}
                </div>
                <input type="submit" value="Keres" class="btn btn-default">
                <div id="rejtett_form" hidden>
                    {{ form.autocomplete_id}}
                </div>
                </form>
            </div>
        </div>
        <br>

        {% if data %}
        <table id="termekek" class="table table-striped" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Gyári cikkszám</th>
                <th>Saját cikkszám</th>
                <th>Termékkategória</th>
                <th>Termék neve</th>
                <th>Bolti bruttó ár</th>
                <th>Link</th>
                <th>Eladás</th>
            </thead>
            <tbody>

            {% for t in termekek %}
            <tr>
                <td width="10%">{{ t.gyari_cikkszam }}</td>
                <td width="10%">{% if t.sajat_cikkszam %} {{ t.sajat_cikkszam }} {% endif %}</td>
                <td width="20%">{{ t.termekkategoria.termekkategoria }}</td>
                <td width="30%">{{ t.termek_nev }}</td>
                <td width="10%">{{ t.ar_bolt_brutto }}</td>
                <td width="10%">{% if t.web_link %} <a href="{{ t.web_link }}">{{ t.web_link }} </a> {% endif %}</td>
                <td>
                    <button style="margin-left:40px;" type="button" class="btn btn-success"
                            onclick="window.location.href='{% url 'termek_ertekesites' pk=t.id %}'">
                        Eladás
                    </button>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}

<script>
    document.getElementById("id_autocomplete_id").value = "";

    $( function() {
    $.ui.autocomplete.prototype._renderItem = function (ul, item) {
        item.label = item.label.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)(" + $.ui.autocomplete.escapeRegex(this.term) + ")(?![^<>]*>)(?![^&;]+;)", "gi"), "<strong>$1</strong>");
        return $("<li></li>")
                .data("item.autocomplete", item)
                .append("<a>" + item.label + "</a>")
                .appendTo(ul);
    };

    $( "#id_autocomplete" ).autocomplete({
      source: "{% url 'get_termek' %}",
      minLength: 2,
        select: function( event, ui ) {
        elem = document.getElementById("id_autocomplete_id").value = ui.item.id;
        document.getElementById("termek_keres_form").submit();
      }
    });
  } );
</script>

{% endblock %}

app/templates/app/termek_atvezetes.html
{% extends "app/layout.html" %}
{% block extrahead %}
<style type="text/css">
    .add-row {
        padding-left:18px;
        background:url(/media/images/add.png) no-repeat left center;
    }
    .delete-row {
        float:left;
        display:block;
        margin:5px 0 0 5px;
        text-indent: 25px;
        background:url(/media/images/delete.png) no-repeat left center;
        width:-1px;
        height:16px;
    }
    tr.row1 td { background-color: #f9f9f9; }
    tr.row2 td { background-color: #f3f3f3; }
    tr.row3 td { background-color: #ededed; }



</style>
{% endblock %}
{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading"><h5 class="panel-title">Termék átvezetés</h5></div>
    <div class="panel-body">
        <h4>Raktári adatok:</h4><br>

        {% if hibas_felvitel %}
            <h4 style="color:red"color>Az alábbi termékeket nem sikerült átvezetni:</h4>
            {% for hiba in hibas_felvitel %}
                - {{hiba}} <br>
            {% endfor %}
        <hr><br>
        {% endif %}

        {% load widget_tweaks %}
        <form method="POST" role="form" id="raktar_form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-2" style="text-align: right;">
                    <h4>Raktárból:</h4>
                </div>
                <div class="col-md-3">
                    {{ form.raktarbol|add_class:"form-control"|attr:"autofocus"|attr:"tabindex:1"}}
                    {{ form.raktarbol.errors }}
                </div>
                <div class="col-md-2" style="text-align: right;">
                    <h4>Raktárba:</h4>
                </div>
                <div class="col-md-3">
                    {{ form.raktarba|add_class:"form-control"|attr:"tabindex:2"}}
                    {{ form.raktarba.errors }}
                </div>
            </div>
        <hr>
        <h4>Termékek:</h4>
        <table id="termekek" class="table table-striped" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Termék</th>
                <!--<th id="th-raktar-felirat">Aktuális készlet</th>-->
                <th>Átvezetendő mennyiség</th>
                <th>Művelet</th>
            </tr>
            </thead>
            <tbody>
            {% for f2 in termekform.forms %}
            <tr id="{{ f2.prefix }}-row">
                <td width="30%">
                    {{ f2.termek_id|add_class:"form-control"|attr:"tabindex:4"}}
                    {{ f2.termek_id.errors }}
                    {{ f2.termek|add_class:"form-control ui-autocomplete-input"|attr:"tabindex:4"|attr:"required"}}
                    {{ f2.termek.errors }}
                </td>
                <!--<td width="10%">-->
                    <!--<input class="form-control" id="aktualis_keszlet">-->
                <!--</td>-->
                <td width="10%">
                    {{ f2.mennyiseg|add_class:"form-control"|attr:"tabindex:6"|attr:"required"}}
                    {{ f2.mennyiseg.errors }}
                </td>
                <td width="10%"></td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        <button style="margin: auto;display:block;font-size: 45px" type="submit" class="btn btn-success"
                onclick="window.location.href='#'" tabindex="9">
            Átvezetés
        </button>
        {{ termekform.management_form }}
        </form>
    </div>

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Figyelmeztetés</h4>
        </div>
        <div class="modal-body">
          <p>A raktárak nem egyezhetenk meg!</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Bezár</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block scripts %}
{{ form.media }}

<script type="text/javascript">
    $(function() {
        $('#termekek tbody tr').formset({
            prefix: '{{ termekform.prefix }}',
        });
    })
</script>

<script>

$.ui.autocomplete.prototype._renderItem = function (ul, item) {
    item.label = item.label.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)(" + $.ui.autocomplete.escapeRegex(this.term) + ")(?![^<>]*>)(?![^&;]+;)", "gi"), "<strong>$1</strong>");
    return $("<li></li>")
            .data("item.autocomplete", item)
            .append("<a>" + item.label + "</a>")
            .appendTo(ul);
};

$(".ui-autocomplete-input").focusin (function() {
    var elem_id = this.id;
    document.getElementById(elem_id).value = "";
    document.getElementById(elem_id+"_id").value = "";
    $("#"+elem_id).autocomplete({
      source: "{% url 'get_termek' %}",
      minLength: 2,
        select: function( event, ui ) {
        elem = document.getElementById(elem_id).value = ui.item.id;
        document.getElementById(elem_id+"_id").value = elem;
      }
    });
  });

$(".ui-autocomplete-input").focusout (function() {
    var elem_id = this.id;
    elem = document.getElementById(elem_id+"_id").value;
    window.setTimeout(function() {
        if (elem == "") {
            document.getElementById(elem_id).value = "";
        }
    },1);
 });

$("#id_raktarbol").change (function() {
    raktarbol = $("#id_raktarbol").val();
    raktarba = $("#id_raktarba").val();
    // th_raktar_felirat = "Aktuális " + $("#id_raktarbol option:selected").text() + " raktárkészlet";
    // $("#th-raktar-felirat").html(th_raktar_felirat);
    window.setTimeout(function() {
        if (raktarbol == raktarba) {
            $("#myModal").modal()
            document.getElementById("id_raktarbol").value = "";
        }
    },1);
 });

 $("#id_raktarba").change (function() {
    raktarbol = $("#id_raktarbol").val();
    raktarba = $("#id_raktarba").val();
    window.setTimeout(function() {
        if (raktarbol == raktarba) {
            $("#myModal").modal()
            document.getElementById("id_raktarba").value = "";
        }
    },1);
 });
</script>

{% endblock %}

app/templates/app/termek_ertekesites.html
{% extends "app/layout.html" %}

{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading"><h5 class="panel-title">Termék értékesítés</h5></div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="col-md-6">
                <h3>Alapadatok: </h3>
                <table id="termek" class="table table-striped" cellspacing="0" width="100%">
                    <tr>
                        <td width="30%"><h4>Termék neve: </h4></td>
                        <td><h4>{{termek.termek_nev}}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Gyári cikkszám: </h4></td>
                        <td><h4>{{termek.gyari_cikkszam}}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Saját cikkszám: </h4></td>
                        <td><h4>{% if termek.sajat_cikkszam %}{{termek.sajat_cikkszam}} {% endif %}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Termék bolti bruttó ára:</h4></td>
                        <td><h4>{{termek.ar_bolt_brutto }} Ft / {{termek.mennyisegi_egyseg}}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Webáruház bruttó ár:</h4></td>
                        <td><h4 id="web_brutto">{{ termek.ar_web_netto}} Ft / {{termek.mennyisegi_egyseg}}</h4></td> <!-- Weben bruttó lett az ár -->
                    </tr>
                    <tr>
                        <td width="30%"><h4>Webáruház nettó ár:</h4></td>
                        <td><h4><span id="web_netto"></span></h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Elhelyezés:</h4></td>
                        <td><h4>{% if termek.elhelyezes%}{{termek.elhelyezes}}{% endif %}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Link:</h4></td>
                        <td><h4>{% if termek.web_link %} <a href="{{termek.web_link}}" target="_blank">{{termek.web_link|truncatechars:50}}</a>
                            {% endif %}</h4></td>
                    </tr>
                    <tr>
                        <td width="30%"><h4>Termék kategóriája:</h4></td>
                        <td><h4>{{termek.termekkategoria.termekkategoria}}</h4></td>
                    </tr>
                </table>
                <Textarea rows="6" class="form-control" placeholder="Megjegyzés">{{termek.megjegyzes}}</Textarea>
            </div>

            <div class="col-md-6">
                <h3>Értékesítés: </h3>
                <div class="col-md-6">
                    {% load widget_tweaks %}
                    <form method="POST" role="form">
                        {% csrf_token %}
                        <h4>Mennyiség: ({{termek.mennyisegi_egyseg}}) </h4>
                        {{ form.eladas_mennyiseg|add_class:"form-control ertekesit_input"|attr:"autofocus"|attr:"tabindex:1"}}
                        {{ form.eladas_mennyiseg.errors }}
                        <h4>Raktár: </h4>
                        {{ form.raktar|add_class:"form-control ertekesit_raktar_input"|attr:"tabindex:3"}}
                        {{ form.raktar.errors }}
                </div>
                <div class="col-md-6">
                    <h4>Eladási ár:</h4>
                    {{ form.ar_eladas_brutto|add_class:"form-control ertekesit_input"|attr:"tabindex:2"}}
                    {{ form.ar_eladas_brutto.errors }}
                </div>
                <div class="top">
                    <button style="margin: auto;display:block;font-size: 45px" type="submit" class="btn btn-success"
                            onclick="window.location.href='#''" tabindex="4">
                        Értékesít
                    </button>
                </div>
                </form>

                <hr>
                <h3>Raktárkészlet információ: </h3>
                <table id="raktar" class="table table-striped" cellspacing="0" width="100%">
                    {% for k in raktarkeszlet %}
                    <tr>
                        <td width="30%"><h4> {{k.raktar}}:</h4></td>
                        <td><h4>{{k.keszlet}} {{termek.mennyisegi_egyseg}}</h4></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

<!--<div class="modal fade" id="myModal" role="dialog">-->
<!--<div class="modal-dialog modal-sm">-->
  <!--<div class="modal-content">-->
    <!--<div class="modal-header">-->
      <!--<button type="button" class="close" data-dismiss="modal">&times;</button>-->
      <!--<h4 class="modal-title">Figyelmeztetés</h4>-->
    <!--</div>-->
    <!--<div class="modal-body">-->
      <!--<p>Nincs elég mennyiség a megadott raktárban</p>-->
    <!--</div>-->
    <!--<div class="modal-footer">-->
      <!--<button type="button" class="btn btn-default" data-dismiss="modal">Bezár</button>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
<!--</div>-->

{% endblock %}

{% block scripts %}
<script>
    // Webáruház nettó árából bruttó számolás és megjelenítés
    ar_web = "{{ termek.ar_web_netto }}";
    ar_web = ar_web.replace(',', '.');
    ar_web = ar_web.replace(/\s+/g, '');
    var ar_web_afa = ar_web / 1.27;
    document.getElementById("web_netto").innerHTML = ar_web_afa.toLocaleString('hu-HU') + " Ft";

    // Eladási ár input mezőbe írás
    ar_bolt = "{{termek.ar_bolt_brutto }}";
    document.getElementById("id_ar_eladas_brutto").value = ar_bolt.replace(/\s+/g, '');

    // Ha a webes ár magassabb mint a bolti akkor piros színnel jelzem
    ar_bolt = ar_bolt.replace(/\s+/g, '');
    ar_bolt = parseFloat(ar_bolt)
    if (ar_web > ar_bolt){
        web_brutto.style.color = "red"
    }

// Ha az eladás nagyobb mint a raktrákészlet
/*
 $("#id_raktarba").change (function() {
    raktarbol = $("#id_raktarbol").val();
    raktarba = $("#id_raktarba").val();
    window.setTimeout(function() {
        if (raktarbol == raktarba) {
            $("#myModal").modal()
            document.getElementById("id_raktarba").value = "";
        }
    },1);
 });
    */
</script>
{% endblock %}